### ISSUE TITLE
execute() not guaranteed to return ResultSet

### ISSUE THREAD

**Issue by jreeseue** [Programming-Systems-Lab/ioclones#1]
Lines 694-696 in `IOUtils.java`:

    totalStmt.execute();
    ResultSet rs = totalStmt.getGeneratedKeys();
    rs.next();

`execute()` here isn't guaranteed to return a `ResultSet` ([PreparedStmt#execute](https://docs.oracle.com/javase/7/docs/api/java/sql/PreparedStatement.html#execute())) so the call to `rs.next()` can fail.

**Comment by jon-bell** [comment]
Thanks for the suggestion  - I added some error checking. If you're trying to use HitoshiIO and having any problems, please let us know - we're still working on getting some better documentation together but are happy to help out.
